<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/9/13
 * Time: 6:17
 */

namespace tests\codeception\unit\models;


use app\modules\frontadmin\forms\IntegrateRechargeForm;
use app\modules\frontadmin\models\user_int_account_flow\User_int_account_flow;
use yii\codeception\TestCase;

class IntegrateRechargeFormTest extends BaseTestCase
{


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->model = new IntegrateRechargeForm();
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function testRecharge(){

        $loginTestForm = new LoginFormTest();
        $loginTestForm->testLoginXhy();

        if($this->model instanceof IntegrateRechargeForm){
            $data = [
                $this->model->formName() => [
                    'amount' => 88,
                    'user_note' => '测试积分账户充值'
                ]
            ];
            $rs = $this->model->recharge($data);
            $message = $this->model->message ? : "调试失败";
            $this->assertTrue($rs, $this->convUtf82Gb2312($message));
        }
    }


    public function testRechargeOk(){
        $loginTestForm = new LoginFormTest();
        $loginTestForm->testLoginXhy();

        if($this->model instanceof IntegrateRechargeForm){

            $flowModel = User_int_account_flow::findOne(53);

            $rs = $this->model->rechargeOk($flowModel, 53);
            $message = $this->model->message ? : "调试失败";
            $this->assertTrue($rs, $this->convUtf82Gb2312($message));
        }
    }

}