<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/9/11
 * Time: 15:04
 */

namespace tests\codeception\unit\models;


use app\modules\common\models\PayOrder;
use yii\codeception\TestCase;

class PayOrderModelTest extends TestCase
{

    private $_model=null;
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->_model = new PayOrder();
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testCreate(){

        $model = $this->_model;
        if($model instanceof PayOrder){

            $rs = $model->create(46,PayOrder::CON_ORDER_TYPE_INT_RECHARGE);

            $message = $model->message ? : ($model->getFirstErrors2String()?:'失败!');
            $message = iconv('utf-8', 'gb2312', $message);

            //删除创建后后置订单
            if($rs){
                $model->delete();
            }
            return $this->assertTrue($rs, $message);
        }
    }


}