<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/3/17
 * Time: 9:28
 */

namespace app\modules\common;


use yii\base\Module;

class CommonModule extends  Module
{

    public $controllerNamespace = "app\modules\common\controllers";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $config = [
            'defaultRoute'  =>  'index',
        ];
        \Yii::configure($this, $config);
    }
}