<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/5/17
 * Time: 19:45
 */

namespace app\modules\common\lib;


use app\modules\jike\controllers\BaseController;
use yii\base\ActionFilter;

class PermissionActionFilter extends ActionFilter
{

    public $operation = null;
    const OPERATION_NOCHECKLOGIN = 'NO';

    public function beforeAction($action)
    {
        if($this->operation == $this::OPERATION_NOCHECKLOGIN){
            BaseController::$isCheckLogin = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}