<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/2/22
 * Time: 21:15
 */

namespace app\modules\jike\models;


use app\ext\common\helpers\MobileMsgAliHelpers;
use app\ext\common\helpers\MobileMsgHelpers;
use app\ext\org\area\AreaTools;
use app\modules\frontadmin\models\user_account\User_account;
use app\modules\frontadmin\service\MessageService;
use app\modules\jike\models\user\User_info;
use yii\base\Exception;
use yii\captcha\CaptchaValidator;
use yii\helpers\ArrayHelper;

class UserRegister extends User
{
    const SCENARIO_REGISTER = 'register';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on($this::EVENT_AFTER_INSERT, [$this, 'afterInseart']);
    }


    /**
     * return tableName
     * @return string
     */
    public static function tableName()
    {
        $user = new User();
        return $user->formName();
    }

    public $captcha;
    public $password;
    public $repeat_password;
    public $mobile_check_code;

    /**
     * return input's placeholder value
     * @return array
     */
    public function getPlaceholder(){
        return [
            'user_name' => '用户昵称或公司简称',
            'captcha' => '输入验证码',
            'user_mobile' => '请输入您的手机号',
            'mobile_check_code' => '输入短信验证码',
            'user_password' => '6-20位数字或字母',
            'repeat_password' => '重复上次的密码'
        ];
    }


    /**
     * return form rules
     * @return array
     */
    public function rules()
    {
        $rules = parent::rules();
        return ArrayHelper::merge($rules, [
            [['user_name','user_mobile','captcha','mobile_check_code','user_password','repeat_password'],'required','on' => self::SCENARIO_REGISTER],
            ['user_name', 'match', 'pattern'=>'/^[(\x{4E00}-\x{9FA5})a-zA-Z_-]+[a-zA-Z0-9_-]*$/u', 'message'=> "用户名必须由英文、数字、下中划线或中文字符组成,且不能以数字开头"],
            ['user_name', 'string','length'=>[2,50], 'message'=>'用户名不能小于4个字符'],
            ['user_mobile', 'string', 'length'=>[11,11], 'message'=>'手机号位数不正确'],
            ['user_mobile', 'match', 'pattern' => '#^1[0-9]{10}$#', 'message'=>'手机号不合法'],
            ['user_mobile', 'unique'],
            ['user_password','string','length'=>[6,20],'message'=>'密码必须为6-20位长度的字符串'],
            ['captcha', 'captcha',  'on'=>self::SCENARIO_REGISTER],
            ['mobile_check_code', 'checkMobileCode'],
            ['repeat_password','compare','compareAttribute'=>'user_password','on'=>self::SCENARIO_REGISTER,'message'=>'密码不一致'],
        ]);
    }

    public function scenarios()
    {
        return [
            self::SCENARIO_REGISTER =>['user_name', 'user_mobile', 'user_password', 'captcha', 'repeat_password', 'mobile_check_code'],
            self::SCENARIO_DEFAULT => [
                'user_name', 'user_mobile'
            ]
        ];
    }

    /**
     * column attributeLabels
     * @return array
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(
            parent::attributeLabels(),
            [
                'user_name' => '用户名称',
                'user_mobile' => '注册手机',
                'mobile_check_code' => '手机验证',
                'captcha' => '验证码',
                'user_password' => '登录密码',
                'repeat_password' => '重复密码',

            ]
        );
    }

    /**
     * validate captcha method
     */
    public function captcha(){

        $captcha = $this->captcha;
        $captchValidator = new CaptchaValidator();
        $captchValidator->captchaAction = '/jike/public/captcha';

        if (!$captchValidator->validate($captcha)) {
            $this->addError('captcha', '验证码错误!');
        }
    }

    /**
     *  validate mobile code
     */
    public function checkMobileCode(){

        if($this->getMobilecode($this->user_mobile) != $this->mobile_check_code ){
            $this->addError('mobile_check_code', "手机验证码不正确!");
        }
    }


    /**
     * register user
     * @param $params
     * @return bool
     */
    public function register($params){
        $this->load($params);
        if( $this->validate() ){
            $trasaction = \Yii::$app->db->beginTransaction();
            try{
                //添加用户
                $rs = $this->save(false);
                $trasaction->commit();
                return $rs;
            }catch(Exception $e){
                $trasaction->rollBack();
                return false;
            }
        } else{
            return false;
        }
    }

    public function getMobileCheckcode($mobile){

        $error = $this->_getMobileCheckcodeHandle($mobile);
        if($error !== true)
            return $error;
        else{
            //生成验证码
            $checkCode = $this->_setMobilecode($mobile);

            //发送验证码，并返回到前端
//            $msg = "【集客】您于".date("Y年m月d日",time())."申请了集客网手机号注册，验证码为{$checkCode}";
//            MobileMsgHelpers::getInstance()->sendMsg([$mobile], $msg);
            MobileMsgAliHelpers::getInstance()->sendMsg([$mobile],MobileMsgAliHelpers::TEMPLATE_REGISTER_CHECK_CODE, ['code'=>$checkCode, 'product'=>'集客']);
            return true;
        }
    }


    /**
     * 设置并返回手机验证码
     * @param $mobile
     * @return int
     */
    private function _setMobilecode($mobile){

        $checkCode = rand(10000,99999);
        $key = 'mobile_check_code_'.$mobile;
        \Yii::$app->session->set($key, $checkCode);
        return $checkCode;
    }

    /**
     * 获取指定手机验证码
     * @param $mobile
     * @return mixed
     */
    public function getMobilecode($mobile){

        $key = 'mobile_check_code_'.$mobile;
        return \Yii::$app->session->get($key);
    }

    /**
     * 获取手机验证码前数据验证
     * @param $mobile
     * @return bool|string
     */
    private function _getMobileCheckcodeHandle($mobile){

        if(! \Yii::$app->request->isGet)

            return "非法请求!";
        else {

            //1.判断手机号是否正确
            if(empty($mobile))
                return "手机号码不能为空!";
            $mobile = trim($mobile);
            if(strlen($mobile) != 11 || !preg_match("#1[\d]{10}#", $mobile))
                return "非法手机号码";
            //2.判断手机号是否已经存在
            if( User::findOne(['user_mobile'=>$mobile]) )
                return "手机号已经存在!";
            else
                return true;
        }

    }


    public function afterInseart($event){

        //1.创建用户信息记录
        $sender = $event->sender;
        $userInfo = new User_info();
        $userInfo->create([
            'user_id' => $sender->user_id,
            'city_id' => AreaTools::getCurrentCityId()
        ]);

        //2. 创建用户账户
        $userAccount = new User_account();
        $userAccount->create([
           'user_id' => $sender->user_id
        ]);

        //3.给用户发送欢迎站内信
        $messageService = new MessageService();
        $messageService->welcomeRegister(User::findOne([$sender->user_id]));

    }

}