<?php
/**
 * 市场营销 controller
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/3/12
 * Time: 20:51
 */

namespace app\modules\frontadmin\controllers;


use app\modules\frontadmin\models\prize_goods\prize_goods;
use app\modules\frontadmin\models\prize_goods\prize_goods_create;
use app\modules\frontadmin\models\PrizeGoods;
use app\modules\frontadmin\service\PrizegoodsService;
use app\modules\frontadmin\service\PrizeOrderService;
use tests\codeception\unit\models\PrizeOrderServiceTest;

class MarketingpromotionController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public  function  actionPrizeRelease(){

        $model = new prize_goods_create();

        $request = \Yii::$app->request;
        if($request->isAjax){

            if($model->create($request->post())){
                returnJson("1","活动发布成功!",[]);
            }else{
                returnJson("0","活动发布失败!",$model->errors);
            }
            exit;
        }
        return $this->render('prizeRelease', ['model' => $model]);
    }

    public function actionPrizegoodsDetail(){

        $id = \Yii::$app->request->get('id');
        $service = new PrizegoodsService();
        $model = $service->getDetail($id);
        p(unserialize( $model->prize_norms_01) );
        p($model);
    }

    public function actionPrizegoodslist(){
        $service = new PrizegoodsService();

        $dataProvider = ($service->getList());

        return $this->render('prizegoodslist', ['dataProvider' => $dataProvider, 'pages'=>$service->getPages()]);

    }

    public function actionTest(){

        $obj = prize_goods::find()->where(['prize_id'=>77])->one();

//        $obj = prize_goods::findOne(12);
//        $video = video::findOne(8);
//        $rs = $video->unlink('prize_goods', $obj, true);
        //$rs = $video->link('prize_goods', $obj);

        p(($obj->videos));
    }

    public function actionOrderList()
    {

        $service = new PrizeOrderService();
        $list = $service->getList();
        $transportList = $service->getTransportList();

        return $this->render('orderlist', [
            'list' => $list,
            'page' => $service->getPages(),
            'transportList' => $transportList
        ]);
    }

    public function actionInfo(){
        return $this->render('info');
    }
}