<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/2/22
 * Time: 18:02
 */

namespace app\modules\jike\controllers;

use app\modules\common\traits\UserinfoTraite;
use app\modules\jike\service\BaseService;
use yii\base\InlineAction;
use yii\web\Controller;

class BaseController extends Controller
{

    use UserinfoTraite;

    public static $isCheckLogin = true;


    public function init()
    {

        $this->layout = 'main';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function createAction($id)
    {
        if ($id === '') {
            $id = $this->defaultAction;
        }

        $actionMap = $this->actions();
        if (isset($actionMap[$id])) {
            return \Yii::createObject($actionMap[$id], [$id, $this]);
        } elseif (preg_match('/^[a-zA-Z0-9\\-_]+$/', $id) && strpos($id, '--') === false && trim($id, '-') === $id) {
            $methodName = 'action' . str_replace(' ', '', ucwords(implode(' ', explode('-', $id))));
            if (method_exists($this, $methodName)) {
                $method = new \ReflectionMethod($this, $methodName);
                if ($method->isPublic() && $method->getName() === $methodName) {
                    return new InlineAction($id, $this, $methodName);
                }
            }
        }

        return null;
    }

    /**
     * 登录检查处理
     */
    protected function _checkLoginHandle(){

        $service = new BaseService();
        if($service->getLoginUserId() == false)

            $this->redirect(\Yii::$app->homeUrl);
    }

    public function setLayoutEmpty(){
        $this->layout = 'main_simple';
    }



}