<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2015/6/24
 * Time: 14:46
 */

namespace app\widgets;


use yii\base\Widget;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\web\View;

class AjaxFileUploadWidget extends Widget{

    public $btnClass='';
    public $inputClass='';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $this->_ajaxUpload($this->btnClass, $this->inputClass);
    }

    /**
     * @param $objClass
     * @param $inputClass
     */
    public function _ajaxUpload($objClass, $inputClass)
    {

        $_csrf = \Yii::$app->request->csrfToken;

        \Yii::$app->view->on(View::EVENT_END_PAGE, function () {

            echo Html::jsFile("@web/js/ext/ajaxFileUpload.js");

            $objClass = $this->btnClass;
            $str = <<<STD

            <script type="text/javascript">

                $.fn.ajaxFileUpload = {

                    init : function(){

                       $.fn.ajaxFileUpload.bindUploadAction();
                       $(document).on("click",'{$this->btnClass}',function(){
                            //触发file input的点击事件
                            $("#"+$(this).attr('point-file-input')).trigger('click');
                       })

                       //删除上传的图片事件
                       $.fn.ajaxFileUpload.delEvent();
                    },

                    //data {id:id, url:url, otherData:otherData}
                    ajaxFileUpload : function(data){
                        var id = data.id;
                        var url = data.url;
                        var otherData = data.otherData?data.otherData:{};
                        var fileDesc = data.fileDesc
                        $.ajaxFileUpload ({
                            url: url,
                            secureuri:false,
                            fileElementId:id,
                            dataType: 'json',
                            data:{_csrf:$("input[name='_csrf']").val(),'fileDesc':fileDesc, id:otherData},
                            success: function (data)
                            {

                                if(data.status==1){
                                    var file_name = data.data.file_name;
                                    var objClass = $('#'+id).attr('point-class');
                                    var showImageId = $('#'+id).attr('point-img');
                                    var pointValueId = $('#'+id).attr('point-valueId-class');

                                    $('.'+objClass).val(file_name);
                                    $('#'+showImageId).attr('src', data.data.img_src).show();
                                    $('.'+pointValueId).val(data.data.upload_id);

                                    $('#'+showImageId).next('.del').css('display','inline-block');
                                }else{
                                    alert(data.message)
                                }
                                return false;

                            },
                            error: function (data, status, e)
                            {
                               alert(e);
                            }
                        });

                        return false;
                    },

                    onFileChange : function(obj){
                        var id = obj.attr('id');
                        var url = obj.attr('data-url');
                        var otherData = {name:id};
                        var fileDesc = obj.parent().find('.file_desc').val();
                        var data = {id:id, url:url,fileDesc:fileDesc,  otherData:otherData};
                        $.fn.ajaxFileUpload.ajaxFileUpload(data);
                    },

                    bindUploadAction : function(){
                        var objClass = '{$this->inputClass}';
                        $(document).on("change",objClass,function(){//修改成这样的写法
                            $.fn.ajaxFileUpload.onFileChange($(this))
                        });
                    },

                    delEvent : function(){
                        $(document).on("click",' .del',function(){
                            //触发file input的点击事件
                            if($(this).prev('{$this->btnClass}').length>0){

                                var fileInputObj = $(this).parent().find('input').eq(0);
                                fileInputObj.val('');

                                var valueInputClass = $(this).parent().find('input').eq(0).attr('point-valueId-class');
                                $('.'+valueInputClass).val('');
                                var src= $(this).prev('$this->btnClass').attr('load-src');
                                $(this).prev('$this->btnClass').attr('src',src)
                                $(this).hide();
                            }
                       })
                    }
                }

            var ajaxFileUpload = $.fn.ajaxFileUpload;
            ajaxFileUpload.init()
            </script>
STD;
            $strBindEvent = <<<STD
STD;
               echo $str.$strBindEvent;
        });

    }




}