<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/4/24
 * Time: 14:39
 */

namespace app\widgets;


use yii\base\Widget;

class AreaPickerWidget extends Widget
{

    public $regions = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return $this->render('area_picker',[
            'regions' => $this->regions
        ]);
    }

}