<?php
/**
 * 地区选择控件
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2015/6/24
 * Time: 14:46
 */

namespace app\widgets;


use yii\base\Widget;
use yii\bootstrap\Modal;
use yii\web\View;

class RegionWidget extends Widget{



    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    public function run()
    {
        if($this->modalType == self::MODAL_TYPE_IFRAME)
            $this->run_iframe();
    }


    /**
     * iframe modal 框架模态弹出窗
     */
    private function run_iframe()
    {

        \Yii::$app->view->on(View::EVENT_END_BODY, function () {


            Modal::begin([
                'id' => 'iframeModal',
                'header' => '<h4 class="modal-title"> Header </h4>',
                'footer' => '<a href="#" class="btn btn-primary" data-dismiss="modal">Close</a>',
                'size' => Modal::SIZE_LARGE
            ]);

            echo '<iframe ></iframe>';

            Modal::end();
        });


    }



}