<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/4/19
 * Time: 22:01
 */

namespace app\modules\api\controllers;


use app\modules\api\models\Region;
use yii\helpers\ArrayHelper;

class RegionController extends BaseApiController
{
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = null;

    }

    public function actionGetArea(){

        $id = \Yii::$app->request->post('id', 1);
        if($id<1){
            $parentIds = Region::find()->where(['=','ParentId',1])->select('ID')->asArray()->all();
            $parentIds = ArrayHelper::getColumn($parentIds,'ID');
            $data = Region::find()->where(['in','ParentId',$parentIds])->asArray()->all();
        }else{

            $data = Region::find()->where(['=','ParentId',$id])->asArray()->all();
        }
        return $this->renderpartial('getArea',['data'=>$data]);
    }

}