<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/2/22
 * Time: 17:54
 */

namespace app\modules\jike;


use yii\base\Module;

class JikeModule extends Module
{

    public $controllerNamespace = 'app\modules\jike\controllers';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $config = [
            'defaultRoute'  =>  'index',
        ];
        \Yii::configure($this, $config);
    }
}