<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/4/19
 * Time: 21:59
 */

namespace app\modules\api;



use yii\base\Module;

class ApiModule extends Module
{

    public $controllerNamespace = 'app\modules\api\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        \Yii::configure($this,[]);
    }

}